travis:
  secure:
    BINSTAR_TOKEN: cPLh6UaREOousVDvJ7nu/xGLBaMzIPHlyJricckCTEwf9lBGSuSEvVAblf3nrNBXpxKQENUp17G6RjV2Q4aBhWQXHcH4qX3hKMO0nK3Tr6b2owOo8BQpZCQkzh1h05uQ0Gn21Poo5VLSDgXkKDnM57iD7qZVbY4P6k7NPrKsBaMMFCdToMAYQUbJJi4JT+j35VS8LSYeeUFGqLVmODf+S2rwA4wZYyxp36U0xP1NgYRgD0OzqtRlbzGLXQsvfyRPy/2tzmYsUebLZxEiZvGqVbcHLc7TVcKmJu1DJH2rFcZ/DqNoAj7p074U5UUWturWoKjCJpG7vEqBdHVi/cyMaYenri8AU8LrqsNF6XkQTEdPU2FDMigvtm2DYYqORpzeQ1i2boPYpTSDwY1G3UmU1eyYf5ssvd29IMzlXV6Tx4fwEvFXOhmTVZehjHZmqXp/xjuqA1IvtsjZAZQ7GBPt6BshmDlFVzDUcZPLeUlEJS00mqxi7CA9xjM10n+jNQgsjJ1BSebPCAtVeE76dHu/TScJG3W7cRoDov+JM0oWcwCuSBCJLuoUkliGHWzL5tW/RTyaCFieNZcUf4b8JPJx+ya/7EW93mB/t0Qe5T+jjYgYP6j9BP1yR48FOfIOEjKWlpGjy2PoJw5S6ozfN5Mz2o8W9sObt9K5TsXMmGkBdP8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
